---
kubernetes_version: "1.29"
kubernetes_apt_key_url: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key"
kubernetes_apt_repo: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/"

pod_cidr: "192.168.0.0/16"
service_cidr: "10.96.0.0/12"
service_dns_domain: "cluster.local"

containerd_version: "2.2.*"
containerd_config_dir: /etc/containerd

calico_version: "v3.27.0"
calico_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml"

ingress_nginx_version: "4.12.0"
ingress_http_nodeport: 30080
ingress_https_nodeport: 30443

argocd_version: "10.3.3"
argocd_namespace: "argocd"
argocd_http_nodeport: 30090
argocd_https_nodeport: 30453
argocd_app_name: "root-app"
gitops_repo_url: "https://github.com/ghassenkhalfallah/k8s-gitops.git"
gitops_repo_path: "apps"
gitops_repo_branch: "main"
gitops_target_namespace: "default"

kubeadm_config_path: /tmp/kubeadm-config.yaml
kubeconfig_path: /etc/kubernetes/admin.conf
local_kubeconfig: "{{ playbook_dir }}/../kubeconfig"

ansible_python_interpreter: /usr/bin/python3
